version: '3'
services:

  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 8080:8080
    environment: 
      - DB_NAME=todousers
      - DB_CONNECTION=mongodb://admin:randompass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:4-focal #I can only run mongo below v5
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/userseeds.js:/docker-entrypoint-initdb.d/userseeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=todousers
      - MONGO_INITDB_ROOT_PASSWORD=randompass
volumes:
  dbdata:
